TWITTER_URL      = 'https://twitter.com/doubleunionsf'
TWITTER_USERNAME = 'doubleunionsf'
PRESS_EMAIL      = 'press@doubleunion.org'
TUMBLR_BASE      = 'doubleunion.tumblr.com'
PAYPAL_EMAIL     = 'paypal@doubleunion.org'
CONTACT_EMAIL    = 'doubleunionsf@gmail.com'
