TWITTER_USERNAME = "doubleunionsf"
TWITTER_URL = "https://twitter.com/#{TWITTER_USERNAME}"

PRESS_EMAIL = "press@doubleunion.org"
PAYPAL_EMAIL = "paypal@doubleunion.org"
JOIN_EMAIL = "join@doubleunion.org"
MEMBERSHIP_EMAIL = "membership@doubleunion.org"
BOARD_EMAIL = "board@doubleunion.org"
KEYS_EMAIL = "keys@doubleunion.org"
SCHOLARSHIP_EMAIL = "scholarship@doubleunion.org"

TUMBLR_BASE = "doubleunion.tumblr.com"
TUMBLR_URL = "http://#{TUMBLR_BASE}"

MAILING_LIST_GENERAL = "https://groups.google.com/a/doubleunion.org/forum/#!forum/public"
GOOGLE_ANALYTICS_ID = "UA-47411942-1"
S3_BUCKET = "https://s3-us-west-1.amazonaws.com/doubleunion"

EXTERNAL_SITE_URL = "https://www.doubleunion.org"
BASE_ASSUMPTIONS_URL = EXTERNAL_SITE_URL + "/base_assumptions"
POLICIES_URL = EXTERNAL_SITE_URL + "/policies"
MEMBERSHIP_URL = EXTERNAL_SITE_URL + "/membership"
ORIENTATION_SIGNUP_URL = "https://www.eventbrite.com/e/new-member-orientation-summer-2019-tickets-63172051306"

KEY_PICKUP_DOC = "https://docs.google.com/document/d/1RYzqGjmA3lLhv9eQzHBg82NVNjik4w_kxi8sKP5ivaY/edit?usp=sharing"
LOCK_UP_DOC = "https://docs.google.com/document/d/1rFoyl5FJjDdr0LqiVacQPuKyj_rsmPpOnAGc77cWTAQ/edit?usp=sharing"
VOTING_CRITERIA_DOC = "https://docs.google.com/document/d/12R7utXAiyCK55XEP8cPscUqu2CXAj-hL5jXE-MaJdgE/edit#heading=h.w83btzy2bttc"
COMMENTING_DOC = "https://docs.google.com/document/d/12R7utXAiyCK55XEP8cPscUqu2CXAj-hL5jXE-MaJdgE/edit#heading=h.ti79qe36hzgp"
VOTING_PROCESS_DOC = "https://docs.google.com/document/d/12R7utXAiyCK55XEP8cPscUqu2CXAj-hL5jXE-MaJdgE/edit#heading=h.y6eimvxrwzvf"
PRONOUNS_GUIDE_URL = "http://www.brynmawr.edu/pensby/documents/AskingforNameandPronouns.pdf"
